PREB-39 added support for imp.ext and added imp.ext.skadn to it
smaato/prebid-server pull request #7
Opened 2023-05-03 16:04 UTC by ioan-alexandru-stef-smaato

The implementation should be straightforward. There is the request.imp[].ext.bidder and request.imp[].ext.skadn. And we copy only the skadn part to impExt, without the bidder params. at https://github.com/smaato/prebid-server/blob/b9f7bab1394593814f61fcf31fb159caedaac069/adapters/smaato/smaato.go#L530

Then the next condition is optional, as the underlying code already checks for JSON errors. at https://github.com/smaato/prebid-server/blob/b9f7bab1394593814f61fcf31fb159caedaac069/adapters/smaato/smaato.go#L534-L540

Then we convert back to JSON, this time only having our impExtData object, containing skadn, and send null if an empty object is created. This is to prevent sending an empty "skadn": {} object to SOMA (performance & resources).

As for the bid response, there were no changes. Our SOMA sends the response exactly as required, and skadn is working correctly (field ext present in OpenRTB bid as json.RawMessage).

Most of the tests were copied and I added skadn fields everywhere (the skadn example is also copied from the example provided by the prebid team), changing the 'sourceapp' in different locations to make sure that the correct req/resp and imps are having the correct values.

2023-05-03 16:07 UTC, ioan-alexandru-stef-smaato commented
We can discuss if docs changes are required. Currently it would be possible to add examples, but I did not find any skadn docs on other adapters.

2023-05-05 06:53 UTC, Enigo requested changes
you need to cover negative cases in test `supplemental` folder

2023-05-05 08:02 UTC, ioan-alexandru-stef-smaato commented
It's a little bit trickier to reproduce an invalid imp.ext. as it can only be checked in adpods.
For imp.ext.skadn. it can be checked directly.

Both checks are only for request, and are only validating the ext and skadn objects to be objects.
There is no validation for responses.

2023-05-05 15:56 UTC, ioan-alexandru-stef-smaato commented
I found it easier to just allow different skadn for adpods' impressions, after all I believe the checks are done in SOMA. And I allowed for invalid ext on following impressions(not the first one), as it should be dealt with in SOMA.
We can change it if you don't like it.

2023-05-09 07:09 UTC, Enigo requested changes

2023-05-09 07:09 UTC, Enigo commented on adapters/smaato/smaato.go
> +		return impExtJson, err
shouldn't it be `return impExtJson, nil`?

2023-05-09 07:09 UTC, Enigo commented on adapters/smaato/smaatotest/videosupplemental/bad-imp-ext-request.json
> +                "ext": {
how is that `bad imp ext`?
looks just fine, more like `missing imp ext skadn` which is already tested by other adpod tests

2023-05-09 07:09 UTC, Enigo commented on adapters/smaato/smaatotest/supplemental/bad-skadn-format-request.json
> +          "skadn": []
this test should also be done for adpod vids

2023-05-09 07:13 UTC, Enigo commented on adapters/smaato/smaato.go
> +// impExt defines Imp.Ext object for Smaato
and also increment the version of the adapter

2023-05-09 07:18 UTC, Enigo commented
> I found it easier to just allow different skadn for adpods' impressions, after all I believe the checks are done in SOMA. And I allowed for invalid ext on following impressions(not the first one), as it should be dealt with in SOMA. We can change it if you don't like it.

On the SOMA side we would only take `skadn` from the first `imp`, I believe, so I guess we should better add it to only first imp to minimize the risk of errors\misconfigs. Also that would make the requests payload smaller
and that change should also have a test coverage

2023-05-11 08:12 UTC, ioan-alexandru-stef-smaato commented
Local tests report a coverage of 94.9%
There is one line that is not possible to cover using tests at:
https://github.com/smaato/prebid-server/blob/7df453cc9d347dcc3379e7f3952fc248d77ca9ee/adapters/smaato/smaato.go#L533

So an alternative would be something like:
```
func makeImpExt(impExtRaw *json.RawMessage) (json.RawMessage, error) {
    skadn, err := jsonparser.GetString(*impExtRaw, "skadn")
    if err != nil {
        return nil, nil
    }

    impExtJson, err := json.Marshal(&impExtData{Skadn: json.RawMessage(skadn)})
    if err != nil {
        return nil, err
    }

    return impExtJson, nil
}
```

2023-05-11 10:03 UTC, Enigo approved these changes
lgtm

2023-05-11 11:15 UTC, closed without merging

2023-05-11 12:12 UTC, el-chuck commented
lgtm